### ISSUE TITLE
Improve definition file loading

### ISSUE THREAD

**Issue by anisf** [cloudera-labs/cloudera-deploy#94]
# Context :
I began to have a huge unreadable definition file, so i wanted to use ansible variables.
I discovered that the definition file was loaded as a simple file, parsed as-is, in yaml. That means variables won't be interpreted (i.e. `host_templates: "{{ cdp_host_templates }}"` will be interpred as string : `"{{ cdp_host_templates }}"`)

My definition file looks like this : 
```yaml
clusters:

- name: "{{ cdp_cluster_name }}"
  type: base
  services: "{{ cdp_services }}"
  databases: "{{ cdp_databases }}"
  configs: "{{ fresh_install_configs }}"
  host_templates: "{{ cdp_host_templates }}"
...
```
# Issue : 
Using variables in the defintion file raises an error due to a check done on the [host_templates here](https://github.com/cloudera-labs/cloudera.cluster/blob/v3.4.0/roles/deployment/groupby/tasks/main.yml#L24)

The error message is : `Unable to host template {{ host_template }} in the cluster definition`

This check is trying to find a host template named 'xxx' in : ``` host_templates: "{{ host_templates }}"``` and fails because it is interpreted as a string...
The [tasks reponsible for this is here
](https://github.com/cloudera-labs/cloudera-deploy/blob/v1.7.0/roles/cloudera_deploy/tasks/distribute_facts_to_inventory.yml#L19)

# Solution : 
Use `include_vars` instead of `lookup(file...)`
